# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 21:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(help_text='Must be over 255 characters', max_length=1000, validators=[django.core.validators.MinLengthValidator(256)]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(help_text='Must be over 255 characters', max_length=1000, validators=[django.core.validators.MinLengthValidator(256)]),
        ),
    ]
