# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditsite', '0002_auto_20160324_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
