# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditsite', '0003_auto_20160324_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=1000),
        ),
    ]
