# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 22:03
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('redditsite', '0007_auto_20160325_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(help_text='Must be over 255 characters', max_length=1000, validators=[django.core.validators.MinLengthValidator(256)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(help_text='Must be over 255 characters', max_length=1000, validators=[django.core.validators.MinLengthValidator(256)]),
        ),
    ]
